name: Update terraform dependencies
on:
  schedule:
    # at 8am PST every day
    - cron:  '* 16 * * *'

jobs:
  dependabot-terraform:
    runs-on: ubuntu-latest
    steps:
      - name: update terraform dependencies
        uses: patrickjahns/dependabot-terraform-action@v1
        with:
          directory: 'terraform/cwe/'
          github_dependency_token: ${{ secrets.DEPENDENCY_GITHUB_TOKEN }}
